In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0
Keras version: 2.2.4-tf


In [2]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


In [3]:
variable = tf.Variable([3, 3])
type(variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [4]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [6]:
x=tf.constant(78)
x

<tf.Tensor: id=17, shape=(), dtype=int32, numpy=78>

In [8]:
x.numpy()

78

In [9]:
x.dtype

tf.int32

In [11]:
x=tf.constant(78, dtype=tf.int64)
x

<tf.Tensor: id=18, shape=(), dtype=int64, numpy=78>

In [12]:
x.dtype

tf.int64

In [14]:
ineuron_x = tf.constant([[4,2],[9,5]])
# print(ineuron_x)
ineuron_x

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]])>

In [15]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]])

In [17]:
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [19]:
tf_ones=tf.ones(shape=(2,2))

In [21]:
print(tf_ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [23]:
print(tf.zeros(shape=(3,4)))

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [24]:
import tensorflow as tf
const2 = tf.constant([[3,4,5], [3,4,5]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


In [25]:
import tensorflow as tf
const2 = tf.constant([[3,4,5], [3,4]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [28]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: id=41, shape=(2, 2), dtype=float32, numpy=
array([[1.0877497 , 0.32833424],
       [2.0062141 , 0.4183344 ]], dtype=float32)>

In [32]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: id=57, shape=(2, 2), dtype=int32, numpy=
array([[7, 6],
       [2, 7]])>

In [33]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [34]:
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [35]:
var_reassign.assign(78)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=78.0>

In [36]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.17932868,  0.59373915],
       [-0.7993128 ,  1.486367  ]], dtype=float32)>


In [42]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
print(a)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.26690358, -0.8411322 ],
       [-1.4398766 ,  0.7849997 ]], dtype=float32)>


In [43]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

In [44]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [45]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: id=453, shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [46]:
## RANK

In [47]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [48]:
tf.rank(tensor)

<tf.Tensor: id=456, shape=(), dtype=int32, numpy=3>

In [50]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

## slicing operation

In [51]:
tensor[0]

<tf.Tensor: id=467, shape=(2, 3), dtype=float32, numpy=
array([[10., 11., 12.],
       [13., 14., 15.]], dtype=float32)>

In [52]:
tensor[1]

<tf.Tensor: id=472, shape=(2, 3), dtype=float32, numpy=
array([[16., 17., 18.],
       [19., 20., 21.]], dtype=float32)>

In [53]:
tensor[0][0]

<tf.Tensor: id=481, shape=(3,), dtype=float32, numpy=array([10., 11., 12.], dtype=float32)>

In [54]:
tensor[0][1][2]

<tf.Tensor: id=494, shape=(), dtype=float32, numpy=15.0>

In [49]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: id=461, shape=(), dtype=float32, numpy=18.0>

In [55]:
print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [56]:
c=tensor.numpy()

In [57]:
c

array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [58]:
type(c)

numpy.ndarray

In [60]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [59]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [61]:
tensor_size = tf.size(input=tensor)
tensor_size

<tf.Tensor: id=501, shape=(), dtype=int32, numpy=12>

In [62]:
# Mathematical Operational

In [63]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.7104386  -1.2112135 ]
 [ 0.8735587   0.18419424]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.15843241 -1.11294   ]
 [-0.21526685 -1.5019338 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.5520062 -2.3241534]
 [ 0.6582918 -1.3177396]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.30471084 5.401689  ]
 [0.43334812 1.7364377 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.5757935  0.09786626]
 [1.9314902  0.2677398 ]], shape=(2, 2), dtype=float32)


In [64]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [65]:
tensor4 = tensor+4
print(tensor4)

tf.Tensor(
[[[14. 15. 16.]
  [17. 18. 19.]]

 [[20. 21. 22.]
  [23. 24. 25.]]], shape=(2, 2, 3), dtype=float32)


In [67]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: id=530, shape=(1, 1), dtype=int32, numpy=array([[64]])>

In [68]:
t2=tf.Variable([[1,2,3],[3,5,5]])

In [71]:
t2.shape

TensorShape([2, 3])

In [73]:
##different dimsnion not suported

In [72]:
t5=tf.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [75]:
t6=tf.Variable([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [76]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


In [81]:
ragged[0,:]

<tf.Tensor: id=830, shape=(4,), dtype=int32, numpy=array([9, 7, 4, 3])>

### Squared difference of tensors

In [82]:
varx = [4,5,6,1,2]
vary = 8
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: id=833, shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

#### Calculate the mean

>Function available
>tf.reduce_mean().

`Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type`

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [83]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])

#### Calculate the mean across all axes

In [84]:
tf.reduce_mean(input_tensor=numbers) #default axis = None

<tf.Tensor: id=836, shape=(), dtype=float32, numpy=5.0>

#### Calculate the mean across columns (reduce rows) with this:

In [85]:
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=838, shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

#### When keepdims = True

In [86]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: id=840, shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

#### Calculate the mean across rows (reduce columns) with this:

In [87]:
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=842, shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

#### When keepdims= True

In [88]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: id=844, shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

####  Random values generation

##### tf.random.normal()

>tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

>The function is as follows:
    
`tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [93]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
randon_num = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(randon_num)

tf.Tensor(
[[12.067193 10.768705]
 [13.823389 14.813833]
 [15.581901  8.200601]], shape=(3, 2), dtype=float32)


####  tf.random.uniform()

>The function is this:
    
>tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

`This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't.

Example:`

In [94]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: id=911, shape=(2, 4), dtype=float32, numpy=
array([[0.12311196, 0.7337725 , 0.7629138 , 0.13405836],
       [0.78359616, 0.19938588, 0.13486528, 0.06176066]], dtype=float32)>

#### Setting the seed

In [97]:
tf.random.set_seed(11)
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 1
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [103]:
tf.random.set_seed(11) #same seed
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 2
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Practical example of Random values using Dices

In [115]:
dice11 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

# lets ADD
dice_sum1 = dice11 + dice12
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

tf.Tensor(
[[ 2  6  8]
 [ 1  6  7]
 [ 1  1  2]
 [ 5  5 10]
 [ 5  1  6]
 [ 2  3  5]
 [ 5  4  9]
 [ 5  2  7]
 [ 3  6  9]
 [ 1  3  4]], shape=(10, 3), dtype=int32)


In [116]:
dice11

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[2],
       [1],
       [1],
       [5],
       [5],
       [2],
       [5],
       [5],
       [3],
       [1]])>

In [117]:
dice12

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[6],
       [6],
       [1],
       [5],
       [1],
       [3],
       [4],
       [2],
       [6],
       [3]])>

>The following functions are available:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [118]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)


i = tf.argmax(input=tensor_1d)
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())


i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',tensor_1d[i].numpy())

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)
index of max;  tf.Tensor(2, shape=(), dtype=int64)
Max element:  51
index of min:  7
Min element:  -19


In [121]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,1,45]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


In [122]:
## TF function

In [123]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

In [131]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph


In [132]:
f1(x,y).numpy()

-78.5

In [133]:

assert f1(x,y).numpy()

In [127]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)

f1(2,3)

<tf.Tensor: id=1460, shape=(), dtype=int32, numpy=75>

In [128]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1(2,3))

TypeError: unsupported callable

In [126]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
func

## Calculate the gradient

### GradientTape

>Another difference from numpy is that it can automatically track the gradient of any variable.

>Open one GradientTape and `tape.watch()` track variables through

In [153]:
##SINCE tape.watch(), different derivate(output) each time below is executed
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a) ## keps on finding derivative
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47196957  0.38429362]
 [ 0.8982984   0.90703493]], shape=(2, 2), dtype=float32)


>For all variables, the calculation is tracked by default and used to find the gradient, so do not `usetape.watch()`

In [154]:
## SINCE NO tape.watch, same derivate (output)

a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.47196957  0.38429362]
 [ 0.8982984   0.90703493]], shape=(2, 2), dtype=float32)


> You can GradientTapefind higher-order derivatives by opening a few more:

In [159]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.45518088 0.59456736]
 [0.1681723  0.1574685 ]], shape=(2, 2), dtype=float32)


# Keras, a High-Level API for TensorFlow 2

![title](img/keras.png)

## The Keras Sequential model

`To build a Keras Sequential model, you add layers to it in the same order that you want the computations to be undertaken by the network.`

`After you have built your model, you compile it; this optimizes the computations that are to be undertaken, and is where you allocate the optimizer and the loss function you want your model to use.`

`The next stage is to fit the model to the data. This is commonly known as training the model, and is where all the computations take place. It is possible to present the data to the model either in batches, or all at once.`

`Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having trained your model, you can use it to make predictions on new data. So, the workflow is: build, compile, fit, evaluate, make predictions.`

`There are two ways to create a Sequential model. Let's take a look at each of them.`

![title](img/kerasmodelling.png)

### Using Sequential model

`Firstly, you can pass a list of layer instances to the constructor, as in the following example.For now, we will just explain enough to allow you to understand what is happening here.`

`Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8-bit integer (uint8), as are the labels:`

#### Loading the datset

In [160]:
mnist_data = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist_data.load_data()

#### Definning the variables

In [161]:
# normalize all the data points and cast the labels to int64
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

In [162]:
train_x

<tf.Tensor: id=2096, shape=(60000, 28, 28), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
     

In [163]:
test_x

<tf.Tensor: id=2098, shape=(10000, 28, 28), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
     

In [164]:
train_y

<tf.Tensor: id=2100, shape=(60000,), dtype=int64, numpy=array([5, 0, 4, ..., 5, 6, 8], dtype=int64)>

#### Building the Architecture 

In [165]:
mnistmodel1 = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])


#### Compiling the model

In [166]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

#### Fitting the model

In [167]:
mnistmodel1.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 11s 176us/sample - loss: 0.2196 - accuracy: 0.9354
Epoch 2/5
60000/60000 [==============================] - 9s 153us/sample - loss: 0.0962 - accuracy: 0.9700
Epoch 3/5
60000/60000 [==============================] - 10s 160us/sample - loss: 0.0672 - accuracy: 0.9787
Epoch 4/5
60000/60000 [==============================] - 10s 165us/sample - loss: 0.0538 - accuracy: 0.9824
Epoch 5/5
60000/60000 [==============================] - 10s 159us/sample - loss: 0.0448 - accuracy: 0.9851


#### Evaluate the mnistmodel1

In [168]:
mnistmodel1.evaluate(test_x, test_y)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.05535711256607901, 0.9819]

>This represents a loss of 0.09 and an accuracy of 0.9801 on the test data. 

>An accuracy of 0.98 means that out of 100 test data points, 98 were, on average, correctly identified by the model.

In [ ]:
The second way to create a Sequential model
The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:



#### Building the Architecture & Compiling

In [171]:
mnistmodel2 = tf.keras.models.Sequential()
mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
mnistmodel2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

#### Fitting the mnistmodel2

In [172]:
mnistmodel2.fit(train_x, train_y, batch_size=64, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 7s 121us/sample - loss: 0.2449 - accuracy: 0.9279
Epoch 2/5
60000/60000 [==============================] - 6s 93us/sample - loss: 0.1055 - accuracy: 0.9684
Epoch 3/5
60000/60000 [==============================] - 6s 92us/sample - loss: 0.0725 - accuracy: 0.9780
Epoch 4/5
60000/60000 [==============================] - 6s 94us/sample - loss: 0.0538 - accuracy: 0.9837
Epoch 5/5
60000/60000 [==============================] - 6s 93us/sample - loss: 0.0445 - accuracy: 0.9858


#### Evaluate the mnistmodel2

In [173]:
mnistmodel2.evaluate(test_x, test_y)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.06407842840193771, 0.9802]

In [177]:
tf.saved_model.save(mnistmodel2,export_dir='C:/Downloads')

NotFoundError: Failed to create a directory: C:/Downloads\variables; No such file or directory

![title](img/kerasmodelling2.png)

### Keras functional API

`The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. It also supports more advanced models. These models include multi-input and multi-output models, models with shared layers, and models with residual connections.`

In [ ]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10


#### Building the Architecture

In [56]:
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

#### Compile & Fit

In [ ]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

#### Evaluate the mnistmodel3

In [ ]:
mnistmodel3.evaluate(test_x, test_y)

### Subclassing the Keras Model class

In [183]:
import tensorflow as tf

#### Building the subclass architecture

In [184]:
class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [185]:
mnistmodel4 = MNISTModel()

#### Compile & Fit

In [186]:
batch_size = 32
# steps_per_epoch = len(train_x.numpy())//batch_size
print(steps_per_epoch)
mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=10)

1875
Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 10s 170us/sample - loss: 0.2218 - accuracy: 0.9344
Epoch 2/10
60000/60000 [==============================] - 9s 157us/sample - loss: 0.0969 - accuracy: 0.9699
Epoch 3/10
60000/60000 [==============================] - 9s 154us/sample - loss: 0.0684 - accuracy: 0.9786
Epoch 4/10
60000/60000 [==============================] - 9s 151us/sample - loss: 0.0545 - accuracy: 0.9826
Epoch 5/10
60000/60000 [==============================] - 9s 150us/sample - loss: 0.0435 - accuracy: 0.9859
Epoch 6/10
60000/60000 [==============================] - 9s 150us/sample - loss: 0.0359 - accuracy: 0.9883
Epoch 7/10
60000/60000 [==============================] - 9s 150us/sample - loss: 0.0319 - accuracy: 0.9894
Epoch 8/10
60000/60000 [==============================] - 9s 150us/sample - loss: 0.0268 - accuracy: 0.9912
Epoch 9/10
60000/60000 [==============================] - 9s 150us/sample - loss: 0.0251 - accuracy: 0.9915

#### Evaluate the mnistmodel4

In [187]:
mnistmodel4.evaluate(test_x, test_y)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.07150129520431638, 0.9824]

In [ ]:
# Keras, a High-Level API for TensorFlow 2

![title](img/keras.png)

## The Keras Sequential model

`To build a Keras Sequential model, you add layers to it in the same order that you want the computations to be undertaken by the network.`

`After you have built your model, you compile it; this optimizes the computations that are to be undertaken, and is where you allocate the optimizer and the loss function you want your model to use.`

`The next stage is to fit the model to the data. This is commonly known as training the model, and is where all the computations take place. It is possible to present the data to the model either in batches, or all at once.`

`Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having trained your model, you can use it to make predictions on new data. So, the workflow is: build, compile, fit, evaluate, make predictions.`

`There are two ways to create a Sequential model. Let's take a look at each of them.`

![title](img/kerasmodelling.png)

### Using Sequential model

`Firstly, you can pass a list of layer instances to the constructor, as in the following example.For now, we will just explain enough to allow you to understand what is happening here.`

`Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8-bit integer (uint8), as are the labels:`

#### Loading the datset

mnist_data = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist_data.load_data()

#### Definning the variables

epochs=10
batch_size = 32

# normalize all the data points and cast the labels to int64
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

#### Building the Architecture 

mnistmodel1 = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])


#### Compiling the model

optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

#### Fitting the model

mnistmodel1.fit(train_x, train_y, batch_size=32, epochs=5)

#### Evaluate the mnistmodel1

mnistmodel1.evaluate(test_x, test_y)

>This represents a loss of 0.09 and an accuracy of 0.9801 on the test data. 

>An accuracy of 0.98 means that out of 100 test data points, 98 were, on average, correctly identified by the model.

The second way to create a Sequential model
The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:



#### Building the Architecture & Compiling

mnistmodel2 = tf.keras.models.Sequential();
mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
mnistmodel2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

#### Fitting the mnistmodel2

mnistmodel2.fit(train_x, train_y, batch_size=64, epochs=5)

#### Evaluate the mnistmodel2

mnistmodel2.evaluate(test_x, test_y)

![title](img/kerasmodelling2.png)

### Keras functional API

`The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. It also supports more advanced models. These models include multi-input and multi-output models, models with shared layers, and models with residual connections.`

import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10


#### Building the Architecture

inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

#### Compile & Fit

optimiser = tf.keras.optimizers.Adam()
mnistmodel3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

#### Evaluate the mnistmodel3

mnistmodel3.evaluate(test_x, test_y)

### Subclassing the Keras Model class

import tensorflow as tf

#### Building the subclass architecture

class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

mnistmodel4 = MNISTModel()

#### Compile & Fit

batch_size = 32
steps_per_epoch = len(train_x.numpy())//batch_size
print(steps_per_epoch)
mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

#### Evaluate the mnistmodel4

mnistmodel4.evaluate(test_x, test_y)